---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 41832.
--- DateTime: 2025/12/7 13:47
---
---@class unlock:object
local id = redis.call("get", KEYS[1])
if (id == ARGV[1]) then
    return redis.call("del", KEYS[1])
end
return 0
